### PR TITLE
- get cached image Bitmap for player cover views

### PR DESCRIPTION
**Pull request by lmj0011**
closes https://github.com/y20k/escapepod/issues/39

### CODE REVIEW

**Comment by lmj0011** [comment]
> But: It also could be that **setImageURI** itself performs worse than setImageBitmap. 

Yes, the problem


> This does Bitmap reading and decoding on the UI thread, which can cause a latency hiccup.

https://developer.android.com/reference/android/widget/ImageView#setImageURI(android.net.Uri)

**Comment by lmj0011** [comment]
In that case we should transform episode.smallCover and episode.cover to bitmap without (double-)resizing.

could also just only have the one uri for podcast/episode cover and let ImageHelper.getPodcastCover do the work resizing/caching. In other words update the DownloadHelper.setPodcastImage function to not do the resizing.

**Comment by y20k** [comment]
This is not exactly my field of expertise. But I feel that storing resized images is probably better than doing the resize again and again. I think I will extend `getPodcastCover` with an option to just convert Uri to Bitmap.

Anyway. Thank you for pointing me to the problems with setImageURI!!! 👍

**Comment by y20k** [comment]
Looking through the code, I found that Escapepod was using `setImageURI` not only in the player element, but also when creating the list (see [setPodcastImage](https://github.com/y20k/escapepod/blob/v0.9.2/app/src/main/java/org/y20k/escapepod/collection/CollectionAdapter.kt#L151)).

I now replaced all instances `setImageURI` with `setImageBitmap` (using the pre-scaled images). See [commit](https://github.com/y20k/escapepod/commit/177a9cb503a8e3dcc136ba02f610fedb2354eecb).

That could indeed increase the scrolling performance.

**Pull request closed without merging**
