### PR TITLE
Remove Yes/No dialog when refreshing

### PR DESCRIPTION
**Pull request by phikal**
This might be a opinionated change (perhaps it should be an configurable option), but it is my understanding that "swiping down" means that the user wants to update whatever they are viewing. Therefore, asking if one is sure is like asking the question twice, despite it not being a critical action that has to be double-checked.

I would just like to note that I couldn't test these changes, since I don't have an IDE (nor do I have enough RAM to use one). So if something pops up, I'm sorry!

### CODE REVIEW

**Comment by y20k** [comment]
Hi @phikal ,

> This might be a opinionated change

Yep :-) Updating a collection of podcasts may (and often does) result in a significant network operation. I think a dialog is necessary here. Also: Pull to refresh might happen accidentally.

**Comment by phikal** [comment]
Ok, so should I look into adding this as an option, or would you rather
not add to many configurable options?

-- 
	Philip K.

**Comment by y20k** [comment]
If like in this case someones donates his/her time and expertise to help to make Escapepod better, it is hard to say no. That is why I recommended in [CONTRIBUTE.md](https://github.com/y20k/escapepod/blob/v0.9.1/CONTRIBUTE.md) to contact me first.
Anyway. I still have to say no here. I want to keep the app super-simple and have a few settings as possible.

**Comment by phikal** [comment]
I totally understand, and it's no problem, especially because the whole
thing took me ~5 minutes to submit.

Thanks anyway for the great app -- it's been a while since I was this
positively impressed by an Android application.

-- 
	Philip K.

**Pull request closed without merging**
